apiVersion: apps/v1
kind: Deployment
metadata:
  name: static1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static1
  template:
    metadata:
      labels:
        app: static1
    spec:
      containers:
        - name: static4
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/coco:latest
          ports:
            - containerPort: 8080
          imagePullSecrets:
          - name: regcred
        - name: static5
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/coco:latest
          ports:
            - containerPort: 8080
          imagePullSecrets:
          - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static1-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static1
                port:
                  number: 8080
  ingressClassName: do-loadbalancer

