name: Build and Push Docker Image
on:
  push:
    branches:
      - master



env:
  DIGITALOCEAN_CLUSTER_NAME: cluster1
  DIGITALOCEAN_NAMESPACE: coolerNamespace
  DIGITALOCEAN_IMAGE_NAME: coco
  DIGITALOCEAN_SERVICE_NAME: flask
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD  }}

      - name: Build and push Docker image
        run: |
          docker build -t rebelpix3l/coco:latest .
          docker push rebelpix3l/coco:latest
      - name: Print deployment file
        run: cat ${{ github.workspace }}//config/deployment.yml
        
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save 7e40d303-cf37-4ab0-b693-7f78f6299617

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f ${{ github.workspace }}/config/deployment.yml
      - name: description
        run: kubectl describe deployment static1
      - name: descrip
        run:     kubectl describe pods -l app=static1
      - name: logs
        run:     kubectl logs
        
      - name: Verify deployment
        run: kubectl rollout status deployment/static1


