name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push Docker image
        run: |
          docker build -t your-docker-username/your-repo:latest .
          docker push your-docker-username/your-repo:latest

      - name: Set up DigitalOcean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.7.0/doctl-1.7.0-linux-amd64.tar.gz | tar xz
          sudo mv ./doctl /usr/local/bin

      - name: Deploy to DigitalOcean
        run: |
          doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
          doctl kubernetes cluster kubeconfig save your-cluster-name
          kubectl apply -f your-deployment-config.yaml
