name: Build and Push Docker Image
on:
  push:
    branches:
      - master



env:
  DIGITALOCEAN_CLUSTER_NAME: k8s-1-26-3-do-0-fra1-1684694904786
  DIGITALOCEAN_NAMESPACE: coolerNamespace
  DIGITALOCEAN_IMAGE_NAME: coco
  DIGITALOCEAN_SERVICE_NAME: flask
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.96.0/doctl-1.96.0-linux-386.tar.gz -O doctl
          chmod +x doctl
          sudo mv doctl /usr/local/bin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD  }}

      - name: Build and push Docker image
        run: |
          docker build -t rebelpix3l/coco:latest .
          docker push rebelpix3l/coco:latest
      
      - name: Deploy to DigitalOcean Kubernetes
        run: |
          doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          doctl kubernetes cluster kubeconfig save $DIGITALOCEAN_CLUSTER_NAME
          doctl kubernetes cluster kubeconfig use $DIGITALOCEAN_CLUSTER_NAME
          kubectl config use-context do-$DIGITALOCEAN_CLUSTER_NAME
          kubectl create namespace $DIGITALOCEAN_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          kubectl set image deployment/$DIGITALOCEAN_SERVICE_NAME $DIGITALOCEAN_SERVICE_NAME=$DOCKER_HUB_USERNAME/$DIGITALOCEAN_IMAGE_NAME:latest -n $DIGITALOCEAN_NAMESPACE


